### ISSUE TITLE
sqlite3.OperationalError: no such table: apps when running install_apps.py

### ISSUE THREAD

**Issue by aiavci** [clover/clover-android-sdk#84]
The readme guide makes you download a script from this repository and run it. However, there's no troubleshooting section and it's making the assumption that a table called 'apps' exists. The script didn't work for me.

**Expected behaviour**
- There's a troubleshooting section with possible problems. e.g. "This script only runs with python version 2".
- There's testing around this script and expectations that not everyone has the schemas ready as assumed in the script

**Comment by nHiRanZ** [comment]
Seeing the same still.

`Getting installed versions...
Getting current app data...
Traceback (most recent call last):
  File "./install_apps.py", line 190, in <module>
    main(sys.argv[1:])
  File "./install_apps.py", line 148, in main
    for row in conn.execute('select * from apps'):
sqlite3.OperationalError: no such table: apps`

**Comment by BhanukaUOM** [comment]
Try this [https://community.clover.com/articles/45689/clover-setup-in-android-emulator.html](https://community.clover.com/articles/45689/clover-setup-in-android-emulator.html)

**Comment by datnthutech** [comment]
> Try this https://community.clover.com/articles/45689/clover-setup-in-android-emulator.html

That's work for me when upload file appinfo.db into path data/data/com.clover.engine/databases on Device Explorer of Android Studio

![image](https://github.com/clover/clover-android-sdk/assets/73189521/5f514d15-59d8-4fe8-81b1-524b1d42be76)

Thank you so much
